### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by fxbenard**
New French translations following wp.org French guidelines for:

- Glossary
- Typo

### CODE REVIEW

**Comment by afragen** [comment]
Thanks @fxbenard 

I need to create translations repositories for the Add-On plugins too. How about that, I already did.

**Comment by fxbenard** [comment]
YW, good idea, even if today pushing translations to a GitHub repo seems so awkward and no productive anymore to me… And definitely no contributions friendly.

**Comment by afragen** [comment]
@fxbenard Are you referring to normal plugins as not being friendly for language contributions or how mine are set up? Just getting clarification.

**Comment by fxbenard** [comment]
What do you mean by normal plugins ;) Those on wp.org ? 
I mean each plugins on GitHub. 
Your LPs are really a nice feature even if it really doesn't change anything in the way to provide translations. 
French translations were years old…

The way to contribute on GitHub is just so complicated. If you aren't a dev you can't really contribute.

Have a GitHub account > Find the Project > Fork it > Translate it in an external software like Poedit > Some Git magic > Create a PR…
Wouah you really need to be motivated to contribute :)

**Comment by afragen** [comment]
I understand. Biggest problem is this plugin still isn't allowed in dot org. I have to rely on translators to be more proactive. Is there a better method for gathering translations for things on GitHub. Is setting up my own GlotPress installation "easier"  😳

**Comment by fxbenard** [comment]
Check out [WP-Translations](https://wp-translations.pro/) and TranslationsPress ;)
That's already available…

**Comment by afragen** [comment]
I made a GlotPress at https://translate.git-updater.com

**Pull request merged**
