### PR TITLE
Update Russian translations

### PR DESCRIPTION
**Pull request by AiratTop**
Now Russian translations are 100% complete and correct. 

I fixed some errors, but used old template (pot-file).

### CODE REVIEW

**Comment by afragen** [comment]
@AiratHalitov thanks. But I think you are not using the updated `/languages/github-updater.pot`. I also do not need the package. I gets created automatically by me.

**Comment by AiratTop** [comment]
> I also do not need the package. I gets created automatically by me.

Ok. You can delete my package and create your own - it's just a zip-archive. :)

When will the translation be merged and available?

**Comment by afragen** [comment]
It looks like I need to update the `ru_RU.po` against the current `github-updater.pot` as the PR is using an outdated source.

**Comment by afragen** [comment]
I pushed an updated version, new strings, of the current `ru_RU.po` file for you to reconcile your commits against. Thanks.

**Comment by AiratTop** [comment]
I updated translations with using new `github-updater.pot` file

**Review by afragen — APPROVED** [review]

**Comment by afragen** [comment]
The PR is showing conflicts and won’t allow me to merge. ☹️

**Comment by AiratTop** [comment]
My last commit https://github.com/afragen/github-updater-translations/pull/21/commits/68d8c022a672f416d59c8b99d65ef7ffdd420e8c is 100% correct. You can completely approve this changes. 
And this your commit https://github.com/afragen/github-updater-translations/commit/697bf392bc47368ed49798bfa0bc12b623ce93a0 isn't needed.

**Comment by AiratTop** [comment]
So how can I help you to merge this PR?

**Comment by afragen** [comment]
It’s late for me. I’ll have to pull the commit down and manually apply it. I’ll fix it in the morning, it’s bedtime now. Thanks.

**Comment by AiratTop** [comment]
I fixed it in https://github.com/afragen/github-updater-translations/pull/22
This PR can be closed

**Pull request closed without merging**
