### PR TITLE
zh_TW Translations Updated

### PR DESCRIPTION
**Pull request by alexclassroom**
zh_TW translations are updated by Alex Lion.

### CODE REVIEW

**Comment by afragen** [comment]
@alexclassroom it looks like you've deleted all the other language files in your PR. That won't work as the PR now wants to delete them from the repo.

The only files you should need to modify are the MO/PO files that you are updating. I will create the zip package.

Additionally, I'm going to update the POT for the next release soon as it's out of date. Not sure when that will be but you should see it in the next week or so.

**Comment by alexclassroom** [comment]
I only unfork my own repository from original and forked it again, then I
submitted updated zh_TW files.

If this action is still wrong, I am so sorry about this.

Attached files are updated zh_TW files.

Regards,

Alex

Andy Fragen <notifications@github.com> 於 2018年5月17日 週四 上午1:30 寫道：

**Comment by afragen** [comment]
I think it's that `delete unnecessary languages` commit (https://github.com/afragen/github-updater-translations/pull/18/commits/fe850a610ec67d6f3dbdf5148ea8cb043fab4a6b) that's causing most of this issue.

And `updated zh_TW package` is not needed either (https://github.com/afragen/github-updater-translations/pull/18/commits/1faa6f8bcad8b1d3b386dfd4584a63d76b0b89da)

**Comment by afragen** [comment]
We can work through this or I you can email me the MO/PO files and I'll create a PR, your choice.

**Pull request closed without merging**
